
# Notes for dd_12529999003.xml
    
 
[drb1] 
lemma = ""
note = "Hans blev konge 1481. Der m√• derfor mangle noget i registraturen, der daterer med romertal (mcdlxxx). Hvilken Kristoffer der er tale om, er usikkert"
