
# Notes for dd_13060726001
[drb1]
  lemma = ""
  note = "egtl. Herrens BÃ¸n tilligemed Hilsen til den hellige Jomfru."
                
[drb2]
  lemma = ""
  note = "jf. DRB II 1 Nr. <a href='/books/dipdan/1257/dd_12570113002'>205</a>. <a href='/books/dipdan/1258/dd_12580915001'>259</a>. <a href='/books/dipdan/1258/dd_12581103001'>261</a>. <a href='/books/dipdan/1261/dd_12610501101'>336</a>. II 2 Nr. <a href='/books/dipdan/1266/dd_12660801002'>21</a>. <a href='/books/dipdan/1278/dd_12781024001'>341</a>. II 4 Nr. <a href='/books/dipdan/1291/dd_12911209001'>43</a>. II 5 Nr. <a href='/books/dipdan/1302/dd_13021029001'>221</a>. <a href='/books/dipdan/1302/dd_13021228001'>227</a>. <a href='/books/dipdan/1305/dd_13050902001'>381</a>."
                