
# Notes for dd_13040318001
[drb1]
  lemma = ""
  note = "jf. Nr. 281 og is√¶r Nr. 304."
                
[drb2]
  lemma = ""
  note = "c. 1. 11. 14 X de filiis presbyterorum ordinandis vel non I 17."
                