
# Notes for dd_13501023001
[drb1]
  lemma = ""
  note = "jf. nr. <a href='../dd_13500508001'>280</a>â€”<a href='../dd_13500508002'>81</a>."
                
[drb2]
  lemma = ""
  note = "jf. DRB II 10 nr. <a href='../dd_13290625001'>124</a>."
                
