
# Notes for dd_11701231101
[drb1]
  lemma = ""
  note = "for datering se Dipl. Dan."
                
[drb2]
  lemma = ""
  note = "jf. Luk. 14, 14."
                
[drb3]
  lemma = ""
  note = "jf. Joh. Ã…benb. 20, 6."
                
[drb4]
  lemma = ""
  note = "jf. Ps. 26, 8."
                
[drb5]
  lemma = ""
  note = "jf. 2. Kor. 6, 11."
                
[drb6]
  lemma = ""
  note = "jf. 2. Tim. 2, 4."
                